=== carlreid/BlockEd/map/MapDTD.dtd
<!--for GGame Version 3.1-->

  <!ELEMENT Game (GameData?, Level+) >
  <!ATTLIST Game name CDATA #IMPLIED >
  <!ATTLIST Game version CDATA "3.1" >

  <!ELEMENT GameData (scroll_area? , controls?) >
      <!ELEMENT scroll_area EMPTY >
      <!ATTLIST scroll_area TripWndX CDATA #IMPLIED>
      <!ATTLIST scroll_area TripWndY CDATA #IMPLIED>
      <!ELEMENT controls EMPTY >

    <!ELEMENT Level (startposition?, exitposition?, MapList*)>
    <!ATTLIST Level id CDATA #REQUIRED >
    <!ATTLIST Level name CDATA #IMPLIED >
      <!ELEMENT startposition EMPTY>
      <!ATTLIST startposition x CDATA #REQUIRED>
      <!ATTLIST startposition y CDATA #REQUIRED>
      <!ELEMENT exitposition EMPTY>
      <!ATTLIST exitposition x CDATA #IMPLIED>
      <!ATTLIST exitposition y CDATA #IMPLIED>

      <!ELEMENT MapList (map+)>
        <!ELEMENT map (layer_offset? , fillcolour? , borderfillcolour? , position? , data? , tile*)>
        <!ATTLIST map name CDATA #IMPLIED >
        <!--<!ATTLIST map z_depth (1|3|5|7|9) #REQUIRED>-->
        <!ATTLIST map z_depth (1|2|3|4|5|6|7|8|9|10) #REQUIRED>
        <!ATTLIST map width CDATA #REQUIRED>
        <!ATTLIST map height CDATA #REQUIRED>
        <!ATTLIST map xsz CDATA "32">
        <!ATTLIST map ysz CDATA "32">
        <!ATTLIST map drawtype (0|1|2|3) #IMPLIED>
        <!--<!ATTLIST map drawtype (0|1|2|3|4|5|6) #IMPLIED>-->
          <!ELEMENT layer_offset EMPTY>
          <!ATTLIST layer_offset x CDATA #REQUIRED>
          <!ATTLIST layer_offset y CDATA #REQUIRED>

          <!ELEMENT fillcolour EMPTY>
          <!ATTLIST fillcolour red CDATA #REQUIRED>
          <!ATTLIST fillcolour green CDATA #REQUIRED>
          <!ATTLIST fillcolour blue CDATA #REQUIRED>
          <!ELEMENT borderfillcolour EMPTY>
          <!ATTLIST borderfillcolour red CDATA #REQUIRED>
          <!ATTLIST borderfillcolour green CDATA #REQUIRED>
          <!ATTLIST borderfillcolour blue CDATA #REQUIRED>

          <!ELEMENT data (#PCDATA)>
  
          <!ELEMENT position EMPTY>
          <!ATTLIST position x CDATA #REQUIRED>
          <!ATTLIST position y CDATA #REQUIRED>

          <!ELEMENT tile EMPTY>
          <!ATTLIST tile sp CDATA #REQUIRED>
          <!ATTLIST tile x CDATA #REQUIRED>
          <!ATTLIST tile y CDATA #REQUIRED>

=== carlreid/BlockEd/map/Dark Depths.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Game SYSTEM "MapDTD.dtd">
<Game name="">
  <GameData>
    <scroll_area TripWndX="0" TripWndY="0" />
  </GameData>
  <Level id="-1" name="Dark Depths">
    <startposition x="200" y="200" />
    <exitposition />
    <MapList>
      <map xsz="32" ysz="32" name="Floor" z_depth="1" width="32" height="32" drawtype="3">
        <layer_offset x="0" y="0" />
        <tile sp="1" x="6" y="6" />
        <tile sp="1" x="6" y="7" />
        <tile sp="1" x="7" y="6" />
        <tile sp="1" x="7" y="7" />
        <tile sp="1" x="7" y="5" />
        <tile sp="1" x="6" y="5" />
        <tile sp="1" x="5" y="6" />
        <tile sp="1" x="5" y="7" />
        <tile sp="1" x="6" y="8" />
        <tile sp="1" x="7" y="8" />
        <tile sp="1" x="8" y="7" />
        <tile sp="1" x="8" y="6" />
        <tile sp="1" x="5" y="8" />
        <tile sp="1" x="8" y="8" />
        <tile sp="1" x="8" y="4" />
        <tile sp="1" x="9" y="4" />
        <tile sp="1" x="9" y="3" />
        <tile sp="1" x="10" y="3" />
        <tile sp="1" x="11" y="3" />
        <tile sp="1" x="12" y="3" />
        <tile sp="1" x="13" y="3" />
        <tile sp="1" x="14" y="3" />
        <tile sp="1" x="14" y="4" />
        <tile sp="1" x="15" y="4" />
        <tile sp="1" x="15" y="5" />
        <tile sp="1" x="15" y="6" />
        <tile sp="1" x="16" y="6" />
        <tile sp="1" x="16" y="7" />
        <tile sp="1" x="16" y="8" />
        <tile sp="1" x="16" y="9" />
        <tile sp="1" x="16" y="10" />
        <tile sp="1" x="15" y="10" />
        <tile sp="1" x="15" y="11" />
        <tile sp="1" x="14" y="11" />
        <tile sp="1" x="13" y="11" />
        <tile sp="1" x="12" y="11" />
        <tile sp="1" x="12" y="12" />
        <tile sp="1" x="12" y="13" />
        <tile sp="1" x="12" y="14" />
        <tile sp="1" x="12" y="15" />
        <tile sp="1" x="13" y="15" />
        <tile sp="1" x="13" y="16" />
        <tile sp="1" x="14" y="16" />
        <tile sp="1" x="12" y="20" />
        <tile sp="1" x="11" y="20" />
        <tile sp="1" x="10" y="20" />
        <tile sp="1" x="9" y="20" />
        <tile sp="1" x="9" y="21" />
        <tile sp="1" x="8" y="21" />
        <tile sp="1" x="7" y="21" />
        <tile sp="1" x="7" y="22" />
        <tile sp="1" x="7" y="23" />
        <tile sp="1" x="11" y="13" />
        <tile sp="1" x="10" y="13" />
        <tile sp="1" x="9" y="13" />
        <tile sp="1" x="8" y="13" />
        <tile sp="1" x="8" y="14" />
        <tile sp="1" x="7" y="14" />
        <tile sp="1" x="7" y="15" />
        <tile sp="1" x="6" y="15" />
        <tile sp="1" x="6" y="16" />
        <tile sp="1" x="5" y="16" />
        <tile sp="1" x="4" y="16" />
        <tile sp="1" x="3" y="16" />
        <tile sp="1" x="2" y="16" />
        <tile sp="1" x="2" y="15" />
        <tile sp="1" x="1" y="15" />
        <tile sp="1" x="1" y="14" />
        <tile sp="1" x="17" y="10" />
        <tile sp="1" x="18" y="10" />
        <tile sp="1" x="19" y="10" />
        <tile sp="1" x="20" y="10" />
        <tile sp="1" x="20" y="9" />
        <tile sp="1" x="21" y="9" />
        <tile sp="1" x="22" y="9" />
        <tile sp="1" x="22" y="8" />
        <tile sp="1" x="22" y="7" />
        <tile sp="1" x="22" y="6" />
        <tile sp="1" x="21" y="6" />
        <tile sp="1" x="21" y="5" />
        <tile sp="1" x="21" y="4" />
        <tile sp="1" x="21" y="3" />
        <tile sp="1" x="16" y="11" />
        <tile sp="1" x="17" y="11" />
        <tile sp="1" x="17" y="12" />
        <tile sp="1" x="18" y="12" />
        <tile sp="1" x="18" y="13" />
        <tile sp="1" x="19" y="13" />
        <tile sp="1" x="19" y="14" />
        <tile sp="1" x="20" y="14" />
        <tile sp="1" x="21" y="14" />
        <tile sp="1" x="21" y="15" />
        <tile sp="1" x="22" y="15" />
        <tile sp="1" x="22" y="16" />
        <tile sp="1" x="23" y="16" />
        <tile sp="1" x="23" y="17" />
        <tile sp="1" x="23" y="18" />
        <tile sp="1" x="23" y="19" />
        <tile sp="1" x="23" y="20" />
        <tile sp="1" x="22" y="20" />
        <tile sp="1" x="22" y="21" />
        <tile sp="1" x="22" y="22" />
        <tile sp="1" x="22" y="23" />
        <tile sp="1" x="22" y="24" />
        <tile sp="1" x="22" y="25" />
        <tile sp="1" x="21" y="25" />
        <tile sp="1" x="20" y="25" />
        <tile sp="1" x="20" y="26" />
        <tile sp="1" x="19" y="26" />
        <tile sp="1" x="18" y="26" />
        <tile sp="1" x="17" y="26" />
        <tile sp="1" x="16" y="26" />
        <tile sp="1" x="16" y="27" />
        <tile sp="1" x="16" y="28" />
        <tile sp="1" x="16" y="29" />
        <tile sp="1" x="22" y="14" />
        <tile sp="1" x="23" y="14" />
        <tile sp="1" x="23" y="13" />
        <tile sp="1" x="24" y="13" />
        <tile sp="1" x="24" y="12" />
        <tile sp="1" x="25" y="12" />
        <tile sp="1" x="26" y="12" />
        <tile sp="1" x="26" y="11" />
        <tile sp="1" x="27" y="11" />
        <tile sp="1" x="27" y="12" />
        <tile sp="1" x="28" y="12" />
        <tile sp="1" x="28" y="13" />
        <tile sp="1" x="29" y="13" />
        <tile sp="1" x="29" y="14" />
        <tile sp="1" x="29" y="15" />
        <tile sp="1" x="30" y="15" />
        <tile sp="1" x="30" y="16" />
        <tile sp="1" x="29" y="16" />
        <tile sp="1" x="29" y="17" />
        <tile sp="1" x="29" y="18" />
        <tile sp="1" x="28" y="18" />
        <tile sp="1" x="27" y="18" />
        <tile sp="1" x="26" y="18" />
        <tile sp="1" x="25" y="18" />
        <tile sp="1" x="24" y="18" />
        <tile sp="1" x="23" y="15" />
        <tile sp="1" x="24" y="14" />
        <tile sp="1" x="25" y="14" />
        <tile sp="1" x="25" y="13" />
        <tile sp="1" x="26" y="13" />
        <tile sp="1" x="27" y="13" />
        <tile sp="1" x="27" y="14" />
        <tile sp="1" x="28" y="14" />
        <tile sp="1" x="28" y="15" />
        <tile sp="1" x="28" y="16" />
        <tile sp="1" x="28" y="17" />
        <tile sp="1" x="27" y="17" />
        <tile sp="1" x="26" y="17" />
        <tile sp="1" x="25" y="17" />
        <tile sp="1" x="24" y="17" />
        <tile sp="1" x="24" y="16" />
        <tile sp="1" x="24" y="15" />
        <tile sp="1" x="25" y="15" />
        <tile sp="1" x="26" y="15" />
        <tile sp="1" x="27" y="16" />
        <tile sp="1" x="26" y="16" />
        <tile sp="1" x="26" y="14" />
        <tile sp="1" x="25" y="16" />
        <tile sp="1" x="27" y="15" />
        <tile sp="1" x="7" y="4" />
        <tile sp="1" x="7" y="3" />
        <tile sp="1" x="8" y="3" />
        <tile sp="1" x="9" y="2" />
        <tile sp="1" x="6" y="4" />
        <tile sp="1" x="8" y="5" />
        <tile sp="1" x="9" y="5" />
        <tile sp="1" x="10" y="4" />
        <tile sp="1" x="10" y="2" />
        <tile sp="1" x="11" y="2" />
        <tile sp="1" x="12" y="2" />
        <tile sp="1" x="14" y="2" />
        <tile sp="1" x="13" y="2" />
        <tile sp="1" x="15" y="3" />
        <tile sp="1" x="16" y="3" />
        <tile sp="1" x="16" y="4" />
        <tile sp="1" x="14" y="5" />
        <tile sp="1" x="15" y="7" />
        <tile sp="1" x="15" y="8" />
        <tile sp="1" x="15" y="9" />
        <tile sp="1" x="17" y="9" />
        <tile sp="1" x="17" y="8" />
        <tile sp="1" x="18" y="9" />
        <tile sp="1" x="19" y="9" />
        <tile sp="1" x="20" y="8" />
        <tile sp="1" x="21" y="8" />
        <tile sp="1" x="21" y="7" />
        <tile sp="1" x="20" y="6" />
        <tile sp="1" x="20" y="5" />
        <tile sp="1" x="20" y="3" />
        <tile sp="1" x="20" y="2" />
        <tile sp="1" x="20" y="4" />
        <tile sp="1" x="14" y="10" />
        <tile sp="1" x="13" y="10" />
        <tile sp="1" x="12" y="10" />
        <tile sp="1" x="11" y="12" />
        <tile sp="1" x="10" y="12" />
        <tile sp="1" x="9" y="12" />
        <tile sp="1" x="8" y="15" />
        <tile sp="1" x="7" y="16" />
        <tile sp="1" x="5" y="17" />
        <tile sp="1" x="4" y="17" />
        <tile sp="1" x="3" y="17" />
        <tile sp="1" x="1" y="16" />
        <tile sp="1" x="11" y="14" />
        <tile sp="1" x="11" y="15" />
        <tile sp="1" x="12" y="16" />
        <tile sp="1" x="13" y="17" />
        <tile sp="1" x="13" y="18" />
        <tile sp="1" x="12" y="18" />
        <tile sp="1" x="11" y="18" />
        <tile sp="1" x="12" y="19" />
        <tile sp="1" x="11" y="19" />
        <tile sp="1" x="10" y="19" />
        <tile sp="1" x="14" y="17" />
        <tile sp="1" x="11" y="21" />
        <tile sp="1" x="10" y="21" />
        <tile sp="1" x="10" y="22" />
        <tile sp="1" x="9" y="22" />
        <tile sp="1" x="9" y="23" />
        <tile sp="1" x="8" y="23" />
        <tile sp="1" x="6" y="23" />
        <tile sp="1" x="6" y="24" />
        <tile sp="1" x="8" y="22" />
        <tile sp="1" x="5" y="24" />
        <tile sp="1" x="4" y="24" />
        <tile sp="1" x="4" y="25" />
        <tile sp="1" x="3" y="25" />
        <tile sp="1" x="3" y="26" />
        <tile sp="1" x="2" y="26" />
        <tile sp="1" x="4" y="26" />
        <tile sp="1" x="5" y="26" />
        <tile sp="1" x="6" y="26" />
        <tile sp="1" x="7" y="26" />
        <tile sp="1" x="8" y="26" />
        <tile sp="1" x="9" y="26" />
        <tile sp="1" x="9" y="27" />
        <tile sp="1" x="9" y="28" />
        <tile sp="1" x="10" y="28" />
        <tile sp="1" x="8" y="27" />
        <tile sp="1" x="2" y="24" />
        <tile sp="1" x="3" y="24" />
        <tile sp="1" x="3" y="23" />
        <tile sp="1" x="3" y="22" />
        <tile sp="1" x="3" y="21" />
        <tile sp="1" x="2" y="21" />
        <tile sp="1" x="2" y="20" />
        <tile sp="1" x="1" y="20" />
        <tile sp="1" x="2" y="22" />
        <tile sp="1" x="2" y="25" />
        <tile sp="1" x="2" y="23" />
        <tile sp="1" x="1" y="21" />
